=== TKussel/SecureEpilinker/data/local-init-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://www.cbs.tu-darmstadt.de/secureepilink/schemas/local-init-schema.json",
  "definitions": {
    "authentication": {
      "properties": {
        "authType": {"enum": ["none","apiKey"]},
        "additionalProperties": {
          "sharedKey": {"type": "string"}
        }
      },
      "required": ["authType"]
    },
    "field": {
      "properties": {
        "name": {
          "type": "string"
        },
        "frequency": {
          "type": "number"
        },
        "errorRate": {
          "type": "number"
        },
        "comparator": {
          "type": "string",
          "enum": [
            "binary",
            "dice"
          ]
        },
        "fieldType": {
          "enum": [
            "integer",
            "number",
            "string",
            "bitmask"
          ]
        },
        "bitlength": {
          "type": "number"
        }
      },
      "required": ["name", "frequency", "errorRate", "comparator", "fieldType", "bitlength"],
      "additionalProperties": false
    }
  },
  "properties": {
    "localId": {"type": "string"},
    "localAuthentication": {"$ref": "#/definitions/authentication"},
    "dataService": {
      "properties": {
        "url": {"type": "string"}
      },
      "required": ["url"],
      "additionalProperties": false
    },
    "algorithm": {
      "properties": {
        "algoType": {"enum": ["epilink"]},
        "threshold_match": {"type": "number"},
        "threshold_non_match": {"type": "number"},
        "exchangeGroups": {"type": "array"},
        "fields": {"type": "array",
          "items": {"$ref": "#/definitions/field"},
          "additionalItems": false}
      },
      "required": ["algoType", "threshold_match", "threshold_non_match", "exchangeGroups", "fields"],
      "additionalProperties": false
    }
  },
  "additionalProperties": false,
  "required": ["localId", "localAuthentication", "dataService", "algorithm"]
}

=== TKussel/SecureEpilinker/test_scripts/inputs/2018-08-24/local_init.json
{
    "algorithm": {
        "algoType": "epilink",
        "exchangeGroups": [
            [
                "vorname",
                "nachname",
                "geburtsname"
            ]
        ],
        "fields": [
            {
                "bitlength": 500,
                "comparator": "dice",
                "errorRate": 0.03999999910593033,
                "fieldType": "bitmask",
                "frequency": 0.009999999776482582,
                "name": "ort"
            },
            {
                "bitlength": 500,
                "comparator": "dice",
                "errorRate": 0.00800000037997961,
                "fieldType": "bitmask",
                "frequency": 2.7100000806967728e-05,
                "name": "geburtsname"
            },
            {
                "bitlength": 5,
                "comparator": "binary",
                "errorRate": 0.004999999888241291,
                "fieldType": "integer",
                "frequency": 0.0333000011742115,
                "name": "geburtstag"
            },
            {
                "bitlength": 500,
                "comparator": "dice",
                "errorRate": 0.009999999776482582,
                "fieldType": "bitmask",
                "frequency": 0.00023499999952036887,
                "name": "vorname"
            },
            {
                "bitlength": 500,
                "comparator": "dice",
                "errorRate": 0.00800000037997961,
                "fieldType": "bitmask",
                "frequency": 2.7100000806967728e-05,
                "name": "nachname"
            },
            {
                "bitlength": 12,
                "comparator": "binary",
                "errorRate": 0.004000000189989805,
                "fieldType": "integer",
                "frequency": 0.028599999845027924,
                "name": "geburtsjahr"
            },
            {
                "bitlength": 4,
                "comparator": "binary",
                "errorRate": 0.0020000000949949026,
                "fieldType": "integer",
                "frequency": 0.08330000191926956,
                "name": "geburtsmonat"
            },
            {
                "bitlength": 80,
                "comparator": "binary",
                "errorRate": 0.03999999910593033,
                "fieldType": "string",
                "frequency": 0.009999999776482582,
                "name": "plz"
            }
        ],
        "threshold_match": 0.95,
        "threshold_non_match": 0.6
    },
    "dataService": {
        "url": "http://192.168.0.103:8066/mainzelliste/Communicator/getAllRecords"
    },
    "localAuthentication": {
        "authType": "apiKey",
        "sharedKey": "123abc"
    },
    "localId": "tud"
}

=== TKussel/SecureEpilinker/test_scripts/configurations/local_init_tuda2.json
{
"localId": "TUDA2",
"localAuthentication": {
  "authType": "apiKey",
  "sharedKey": "123abc"
},
"dataService": {
  "url": "http://127.0.0.1:8800/Communicator/getAllRecords"
},
"algorithm": {
  "algoType": "epilink",
  "threshold_match": 0.9,
  "threshold_non_match": 0.7,
  "exchangeGroups": [[ "vorname", "nachname", "geburtsname" ]],
  "fields": [
    {
    "name": "vorname",
    "frequency": 0.000235,
    "errorRate": 0.01,
    "comparator": "dice",
    "fieldType": "bitmask",
    "bitlength": 500
    },
    {
    "name": "nachname",
    "frequency": 0.0000271,
    "errorRate": 0.008,
    "comparator": "dice",
    "fieldType": "bitmask",
    "bitlength": 500
    },
    {
    "name": "geburtsname",
    "frequency": 0.0000271,
    "errorRate": 0.008,
    "comparator": "dice",
    "fieldType": "bitmask",
    "bitlength": 500
    },
    {
    "name": "geburtstag",
    "frequency": 0.0333,
    "errorRate": 0.005,
    "comparator": "binary",
    "fieldType": "integer",
    "bitlength": 11

    },
    {
    "name": "geburtsmonat",
    "frequency": 0.0833,
    "errorRate": 0.002,
    "comparator": "binary",
    "fieldType": "integer",
    "bitlength": 11

    },
    {
    "name": "geburtsjahr",
    "frequency": 0.0286,
    "errorRate": 0.004,
    "comparator": "binary",
    "fieldType": "integer",
    "bitlength": 11

    },
    {
    "name": "plz",
    "frequency": 0.01,
    "errorRate": 0.04,
    "comparator": "binary",
    "fieldType": "string",
    "bitlength": 40

    },
    {
    "name": "ort",
    "frequency": 0.01,
    "errorRate": 0.04,
    "comparator": "dice",
    "fieldType": "bitmask",
    "bitlength": 500

    }]
  }
}
